# =============================================================
# DISCORD ANTINUKE SELFBOT CONFIGURATION
# =============================================================
# INSTRUCTIONS:
# 1. Replace the example values with your own information
# 2. Save this file
# 3. Start the selfbot
# =============================================================

# YOUR ACCOUNT AND SERVER SETTINGS
selfbot:
  # PUT YOUR DISCORD TOKEN HERE (NEVER SHARE THIS WITH ANYONE)
  token: ""
  
  # SERVERS TO PROTECT (GET THESE IDS BY RIGHT-CLICKING THE SERVER > COPY ID)
  server1_id: ""  # First server to protect
  server2_id: ""  # Second server to protect (you can leave this empty)
  
  # WHO GETS NOTIFICATIONS (GET THESE IDS BY RIGHT-CLICKING YOUR PROFILE > COPY ID)
  owner1_id: ""  # Your user ID
  owner2_id: ""  # Another user ID (optional)
  
# PROTECTION SETTINGS - WHAT HAPPENS WHEN SOMEONE RAIDS
antinuke_settings:
  # WHAT TO DO WHEN SELFBOT DETECTS AN ATTACKER
  punishment: "ban"  # Options: "ban", "kick", or "none"
  
  auto_recovery: true # Automatically recover the channels and roles that were harmed
  recover_channels: true  # Recover deleted channels
  recover_roles: true     # Recover deleted roles
  recovery_delay: 1500     # Milliseconds to wait between recoveries
  
  # HOW MANY ACTIONS TRIGGER THE PROTECTION
  # If someone does more than this number of actions in the time window, they're caught
  ban_limit: 5                # Triggers if someone bans 5+ people quickly
  kick_limit: 5               # Triggers if someone kicks 5+ people quickly
  channel_create_limit: 5     # Triggers if someone creates 5+ channels quickly
  role_create_limit: 5        # Triggers if someone creates 5+ roles quickly
  channel_delete_limit: 5     # Triggers if someone deletes 5+ channels quickly
  role_delete_limit: 5        # Triggers if someone deletes 5+ roles quickly
  channel_update_limit: 5     # Triggers if someone changes 5+ channels quickly
  role_update_limit: 5        # Triggers if someone changes 5+ roles quickly
  member_update_limit: 5      # Triggers if someone changes 5+ members quickly
  unban_limit: 5              # Triggers if someone unbans 5+ people quickly
  
  # TIME WINDOW FOR COUNTING ACTIONS (IN MILLISECONDS)
  # 36000000 = 10 hours, 3600000 = 1 hour, 600000 = 10 minutes
  time_window: 36000000    

# LOGGING SETTINGS - WHERE TO SEND ALERTS
logs:
  # OPTIONAL DISCORD CHANNEL ID FOR LOGGING
  channel_id: ""
  
  # WHAT TYPES OF EVENTS TO LOG
  log_level: "info"  # Options: "all", "info", "warning", "error", "critical"
  
  # SHOW TIMESTAMPS IN LOGS?
  timestamp: true
  
  # WEBHOOK URL FOR SENDING LOGS (LEAVE EMPTY IF NOT USING)
  log_webhook: ""
  
  # SEND DM TO OWNERS WHEN IMPORTANT THINGS HAPPEN?
  log_owner_dm: false  # Set to true to get DM alerts

# USERS WHO WON'T TRIGGER THE PROTECTION
# Add IDs of trusted admins you want to exclude from checks
whitelisted:
  users: [""]

# ACTIVITY STATUS SETTINGS
rpc:
  # SHOW "WATCHING SERVERS" OR SIMILAR STATUS?
  enabled: true
  
  # AUTOMATICALLY CHANGE STATUS MESSAGE?
  rotation: false

# =============================================================
# For help with setup, join: https://discord.gg/heer
# Made with ❤️ by faiz4sure
# =============================================================